### ISSUE TITLE
20161218-Stuttgart-hackathon

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/bc-climate-explorer#1]
# 2016-12-18-Stuttgart-Hackathon-Goals

As a first meeting for the re-development phase of the BC Climate Explorer, @kevinkl and I met in Stuttgart to do a code review, data structure overview, and redesign of the current app into a dashboard tool for scientists. 

A basic overview of our goals are as follows:
* [x] redesign the interface ==> tool
* [X] code review
* [X] data structure review
* [x] research phase 
* [x] restructuring code:
	- we don't need a server ==> host on github pages :)
	- better readable + modular 
	- framework? maybe not?
        - use gulp or grunt to compile JS scripts?
        - if  the data changes, we should try not to change the code, just change the data set name

**Comment by cmahony** [comment]
great to hear that you guys met up in person. stoked to work on this with you in the new year!
c

**Comment by joeyklee** [comment]
@cmahony it was really nice. we even had a chance to go to the christmas market ;)

**Comment by joeyklee** [comment]
Going to close this now as I think we've covered these issues.
