### ISSUE TITLE
Grunt setup: default not found

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/bc-climate-explorer#11]
When trying to run `grunt` i get the following:

```
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.

```

Any ideas?

**Comment by kevinkl** [comment]
Oh snap, I forgot to add the grunt default command, I will add it as soon as possible ;) 
Try `grunt serve` instead.

**Comment by joeyklee** [comment]
Thanks @kevinkl !!
