### ISSUE TITLE
Sprint Planning

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/bc-climate-explorer#12]
It's time to do a re-design and implementation of the project. Ideally we can timebox it and get a new version up and running, fresh and ready to go.

A mix of implementation thoughts here:

<s>
- [ ] React + Redux :
    + As I've been working in React these days, maybe it does make sense to give this a go. 
    + testing ... yes it is about time to do tests
- [ ] Revisit the designs to clean up
    + a lot of time has passed // good to clean up and define aesthetics // fonts, styles, etc
- [ ] Data processing and workflow:
    - map data: switch to mapbox vector tiles + tilehut.js instance on digital ocean for map data
    - climate data: serve data via mongo // pre-process everything to save computation
    - with redux we can finally control our state in a better way

### First steps:

- [x] 0. Designs
- [ ] 1. create layout + styles for "components"
- [ ] 2. wire front end up as react components & dummy data
- [ ] 3. setup backend & workflow for data handling
</s>

**^^ dropped those ideas above for now**

**Comment by joeyklee** [comment]
Status update:

Currently working on layout and getting the styles right before looking into wiring up the backend.

![screenshot-2018-5-2 layout template](https://user-images.githubusercontent.com/3622055/39548343-55dc0bee-4e28-11e8-8460-457d9a633505.png)

**Comment by cmahony** [comment]
cool! i'll be on standby for a discussion on how best to structure the data. 
colin

**Comment by joeyklee** [comment]
Updates:
1. Experimented with Mapbox vector tiles - we've got a smooth zooming map 
2. the charts are now wired to the data hosted on Carto (we can evaluate if we want to change this. For now, just testing for functionality)
3. The charts all update on selection using dropdowns. Still need to implement Log functionality

Todo's on my mind:
1. [x] develop a map color scheme that reflects the BEC system (e.g. hot, dry == warmer colors)  ==> generate style.json
2. [x] style chart axes + add labels
3. [x] still need to add in projections data
4. [x] do some tests to see how much data we can pack into the vector tiles
5. [x] need to add map button functionality 
6. [x] legends for map 
7. [ ] create landing page /intro to application 

Addtional:
+ for now, just going through using JQuery to handle everything event-based as it was in the last version. This will change if/when we decide to use something like React w/ Redux. 

![screenshot-2018-5-4 layout template 1](https://user-images.githubusercontent.com/3622055/39658028-49278b3e-4fdc-11e8-9bba-f47385c926be.png)

**Comment by cmahony** [comment]
sweeeeeeeeeeet!

**Comment by kevinkl** [comment]
Sorry for the late response. It looks awesome!!!

I will look over the stuff you made tomorrow, just out of curiosity :D

**Comment by joeyklee** [comment]
Hi all! 

Just a quick update from my side:
1. Working through some refactoring. Current prototyping is getting a little unwieldy and will spend some time to clean it up for easier discussion and later iterations of refactoring. hooray for refactoring! I'll be implementing a pub/sub pattern so @kevinkl should be able to help out here!  Some of the points I'm hoping to address is to deal with all of the reactivity we're passing back and forth between components. see below

![screenshot-2018-5-8 layout template](https://user-images.githubusercontent.com/3622055/39826919-53032f18-5384-11e8-91f7-6cfdd2963113.png)

2. Tomorrow is the global sprint - I will be working from NYC on this project :) My goal will be to have something up on the web so we can discuss with as much functionality in place as possible + with the existing backend infrastructure (e.g. carto hosting for data + mapbox vector tiles) 

3. Spent a bit of time working on some more appropriate map colors. We can discuss the next days once the prototype is up (hopefully after the sprint!)

<img width="704" alt="screen shot 2018-05-09 at 12 29 00" src="https://user-images.githubusercontent.com/3622055/39827034-afa310f8-5384-11e8-8812-2677f51a2a78.png">
<img width="706" alt="screen shot 2018-05-09 at 12 29 05" src="https://user-images.githubusercontent.com/3622055/39827035-afb58a62-5384-11e8-8208-ed0de0c6255e.png">
<img width="718" alt="screen shot 2018-05-09 at 12 29 09" src="https://user-images.githubusercontent.com/3622055/39827036-afc8442c-5384-11e8-91a4-fc5e245f6c25.png">
<img width="695" alt="screen shot 2018-05-09 at 12 29 14" src="https://user-images.githubusercontent.com/3622055/39827038-b075da1a-5384-11e8-961a-e7ed55f6268c.png">


Progess is steady.

**Comment by kevinkl** [comment]
Looks really great! Can't wait to chat with you about this

**Comment by cmahony** [comment]
Hey @joeyklee , 
looks awesome! 
There is a standard color scheme for BEC zones, which we should use. i added this as a csv file in the assets folder of the repository: BGCzone_Colorscheme.csv. 
for the other color schemes, feel free to delegate this to me iff you like... it seems like one of the few things that i'm technically competent to help with. 
very looking forward to working with you guys on this. 
c

**Comment by joeyklee** [comment]
Thanks @cmahony! I will check it out and incorporate.
Will keep you updated!

**Comment by joeyklee** [comment]
WHEW! Ok! So after sprinting we've got a few things up and running and much more stable than before. It'll be great to figure out strategies for optimizing with @kevinkl 

Anyhow. I think we're in a good place to have a first discussion about feelings and features. It's still pretty raw, but there's some major differences from the first version which I think are noteworthy:

1. running HTTPS 
2. All charts are visible at the same time & reactive
3. Searching and filtering are enabled for the dropdowns
4. Users can take photos of the charts
5. Bec Units are styled and colors using the subUnit values to modulate color to still give feeling of relation to the base BecZone colors
6. Colors for temperature and precipitation are different + method is in place to style them according to https://github.com/joeyklee/bc-climate-explorer/issues/6

Again, there's still a bunch of things to do:
1. [X] add climate projections data
2. [X] add map interactions
3. [X] add reactivity for hover between scatterplot and map
4. make the landing page
5. make more usable legend
6. full screen functionality would be great for each graph.
7 ... 

Let's chat next week! @cmahony and @kevinkl 

See: https://joeyklee.github.io/bc-climate-explorer/ 

![screenshot-2018-5-11 bc-climate-explorer](https://user-images.githubusercontent.com/3622055/39950723-5388ca50-5551-11e8-9147-6491edb8b910.png)

**Comment by kevinkl** [comment]
Sounds like a great plan. Let's chat next week!

**Comment by cmahony** [comment]
Awesome Joey! Talk to you guys next week  
C

**Comment by joeyklee** [comment]
Moving these issues to individualized issues to tackle. Will close for now.
