### ISSUE TITLE
Tool interface layout - feedback wanted

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/bc-climate-explorer#3]
After our little hackathon, we put together this basic layout for what we might imagine the tool to look. We made some decisions about what we want to interface to look like and how we want people to be able to work with the data. Feel free to comment in this thread.
[wireframes-JLEE-20161218.pdf](https://github.com/joeyklee/bc-climate-explorer/files/667071/wireframes-JLEE-20161218.pdf)

**Comment by cmahony** [comment]
this is beautiful and looks well thought out. i'll give some detailed comments tomorrow.

**Comment by cmahony** [comment]
@joeyklee @kevinkl 
great to see this new layout.  I really like the compact approach. i have a few comments, though i'm cognizant that i'm unaware of many of the considerations and compromises that went into this wireframe, so take these thoughts for what they are worth. 

i have reservations about the top bar, which requires users to enter a whole bunch of info before they get started ("GO"). for example, a user that only wants to see the time series for a single location will be required to enter and then see a bunch of other information that isn't relevant to them (scatterplot, second location). I envision a user experience that starts simple and gets richer and more complicated as the user becomes more comfortable with the tool. 
- We could achieve a lot of simplicity if the plots were mutually exclusive (one off while the other on). almost all users will be happy to explore one plot type at a time. the plots contain a lot of info, and it would be good to maximize the space they have. also each plot has its own controls, which could be visible only when the plot is active. 
- Perhaps we toggle the secondary unit functionality. the main thing is to have one unit as a default, and a secondary unit as an option. 

We may end up wanting more controls for the map. there are two types of information that can be displayed on the map, (each with some variants): BEC units (zone or unit), or climate variables (historical normals, projected normals, or amount of change). 

This isn't a layout thing, but just as a heads up, I think that we will end up only wanting one RCP at a time (a single RCP will allow us to show model uncertainty), so RCP may be an additional selection box.

I hope these ideas are helpful. it's great to be working on this again!

Colin

**Comment by kevinkl** [comment]
Thanks for the feedback Colin. 

@joeyklee could you send me the Sketch source file of the wireframes. I want to show you guys some things I would change regarding the ideas of Colin.

**Comment by joeyklee** [comment]
@cmahony thanks for the feedback! Duly noted. Will use this as a way to do another iteration. With the holidays, however I will be out of commission for the next 2 weeks.

@kevinkl I've added the sketch source files to the repo. You will see them in the `assets` folder :) Thanks!!

**Comment by joeyklee** [comment]
@cmahony @kevinkl  - just fyi, I put a new set of wireframes reflecting the discussion ^^. Please see: https://github.com/joeyklee/bc-climate-explorer/blob/master/assets/wireframes/wireframes-JLEE-20170107.pdf

Hope your new years are off to a great start!

@kevinkl - I know it is end of term for you, so no worries! Just wanted to keep you up to date with the progress :)

**Comment by kevinkl** [comment]
@joeyklee Thanks for your patience with me :) As soon as the projects are finished (hopefully at the end of January) I will start with the skeleton for the tool! I got some helpful tips from my colleague, can't wait to start to put them to code. 

I like the new wireframes, great work!

You guys will hear from me soon.

**Comment by joeyklee** [comment]
Sure thing! Good luck with your presentation and projects! 💪

Looking forward to hearing about how things went + your new ideas for the skeleton :)

-J

**Comment by cmahony** [comment]
@joeyklee thanks for the new wireframes and apologies for the delayed reply. Looking back over my comments, i think i may have misled you: when i said "explore one plot type at a time" i was referring only to the scatterplot vs time series plot. i think it is important that the map is always there, plus one plot; just like in our beta version. being able to put the plots into spatial context is the thing that makes this tool so great. i think the new compact layout is great though. maybe once kevin is back on scene we can put our heads together over skype and finalize the wireframing. 
i hope all is well!
-c

**Comment by kevinkl** [comment]
Hey you two, I have good news. Today was the deadline for our projects and I have more or less finished them. So I am back! Do you guys have time on Friday?

**Comment by cmahony** [comment]
congrats on finishing your projects @kevinkl! friday is great for me.

**Comment by joeyklee** [comment]
Hi! Nice! 🎉
How about something like 5pm CEST / 8AM PST? Via Skype?

-J

**Comment by kevinkl** [comment]
Thanks!! Tomorrow 5pm CEST / 8AM PST is fine with me.

**Comment by cmahony** [comment]
8am is feeding time and us zookeepers are all hands on deck. any chance we could move it to 845? sorry, i realize that pushes you guys towards dinner time

**Comment by kevinkl** [comment]
8:45 AM PST? That's also fine with me, no problem.

**Comment by joeyklee** [comment]
Ok - then let’s do 8:45-9:15 PST / 17:45 - 18:15 CEST. Cool?

-J

**Comment by cmahony** [comment]
oui, c'est cool! thanks for accommodating me.

**Comment by joeyklee** [comment]
Hi @cmahony and @kevinkl - i posted the latest set of wireframes based on what we talked about in our last chat here: https://github.com/joeyklee/bc-climate-explorer/blob/master/assets/wireframes/wireframes-JLEE-20170201.pdf

let me know what you think!

**Comment by joeyklee** [comment]
the 1 thing I haven't decided on is the climate variables for the map - still need to think about how to allow climate variable exploration...

**Comment by cmahony** [comment]
YES! This looks superb. very nice to have all the information on the one dashboard. one idea i have is that the user could click on one of the time series to expand it upwards for more detailed viewing. i'll send more detailed comments tomorrow, but just want to say... Great Success!!

**Comment by cmahony** [comment]
Hi again, 
after going over the wireframe in detail, i don't see any problems. you've come up with a great approach here. looking forward to discussing the details on skype. 
We need to give special attention to how we manage the secondary unit. the 2nd unit is important, but will be confusing for a lot of users as they start. perhaps as a default, the user only selects unit A, and unit B shows up on hover-over. something to discuss on skype as well. 
colin

**Comment by kevinkl** [comment]
Hi,

a Skype call would be great again, because I also have some results on the structure/development side that I want to show you.

@cmahony and @joeyklee when do you two have time? 

-K

**Comment by kevinkl** [comment]
Sorry I accidentally closed the issue :)

**Comment by cmahony** [comment]
hi both, I'm free anytime after 515pm german time (815am PST) on tuesdays and thursdays, 545pm (845am PST) on mondays, wednesdays, and fridays.

**Comment by kevinkl** [comment]
Ok,  I am free next Thursday (2/9/2017) at 5:30Cest/8:30 PST. What about you @joeyklee?

**Comment by joeyklee** [comment]
Hi sorry for the late reply - was away this weekend. 17:30CEST / 8:30PST should be fine for me. See you all then!

**Comment by joeyklee** [comment]
Hi All, I think I've integrated the feedback from our chat. I made 1 change though which was to instead of having a "+" button for the secondary unit, just created a transparecy/grey-out for that button. 

see the latest here: https://github.com/joeyklee/bc-climate-explorer/blob/master/assets/wireframes/wireframes-JLEE-20170209.pdf

**Comment by cmahony** [comment]
joey, sorry for the late response. the wireframes look great. perhaps it goes without saying, and not necessary to put on the wireframe. but we will also need some tabs for the supporting information (about, help, data).

**Comment by joeyklee** [comment]
@cmahony - I will work them in! cheers!

**Comment by joeyklee** [comment]
Closing this for now.
